name: chattracker
version: 1.0-BigBrother
main: yomikey.chattracker.Chattracker
api-version: '1.21'

commands:
  chattracker:
    description: Test command for the ChatTracker plugin
    usage: /chattracker

  staffchat:
    description: Send a private message to all staff
    usage: /staffchat <message>
    aliases: [sc]

permissions:
  chattracker.staffchat:
    description: Access to staff chat
    default: op
