name: ChatTracker
version: 1.0
main: yomikey.chattracker.Chattracker
api-version: 1.21

commands:
  chattracker:
    description: Check if ChatTracker is working
    usage: /<command>
  staffchat:
    description: Send a message to staff chat or toggle it
    usage: /<command> [message]
  setrank:
    description: Set a player's rank in ChatTracker
    usage: /setrank <player> <rank>
  resetrank:
    description: Reset a player's rank to default/config
    usage: /resetrank <player>
  report:
    description: Report a chat message to staff
    usage: /report <player> <message>
